### PR TITLE
Fixed Internal server error on woocommerce subscription purchase

### PR DESCRIPTION
**Pull request by monishdeb**
Please check https://github.com/WPCV/wpcv-woo-civi-integration/issues/30 for detail

### CODE REVIEW

**Comment by christianwach** [comment]
@monishdeb Thanks for this. Couple of things:

* I'd prefer an approach that uses the second param when it's present - i.e. `order_updated( $order_id, $order = null )` etc...
* Can you run your new code through `phpcs` so it matches the codestyle for this repo?

Thanks!

**Comment by monishdeb** [comment]
@christianwach yes I tried this fix earlier : 
```diff
diff --git a/wp-content/plugins/wpcv-woo-civi-integration/includes/classes/class-woo-civi-source.php b/wp-content/plugins/wpcv-woo-civi-integration/includes/classes/class-woo-civi-source.php
index 5b09ebed3..b575268e6 100644
--- a/wp-content/plugins/wpcv-woo-civi-integration/includes/classes/class-woo-civi-source.php
+++ b/wp-content/plugins/wpcv-woo-civi-integration/includes/classes/class-woo-civi-source.php
@@ -149,7 +149,7 @@ class WPCV_Woo_Civi_Source {
         * @param integer $order_id The Order ID.
         * @param object  $order The Order object.
         */
-       public function order_updated( $order_id, $order ) {
+       public function order_updated( $order_id, $order = null) {
 
                if ( ! is_admin() ) {
                        return;
```
but didn't work for me. Am I missing something here?

**Comment by christianwach** [comment]
@monishdeb Try https://github.com/christianwach/wpcv-woo-civi-integration/commit/00cfe0c154c6990466c7a960bca73174eab2b6b0 - it seems `woocommerce_new_order` suffers from the same inconsistency.

**Comment by monishdeb** [comment]
Yay, it worked for me. Thank you so much for sharing the patch. 

I am closing this PR

**Pull request closed without merging**
